### ISSUE TITLE
Clean up navigation bar

### ISSUE THREAD

**Issue by DorinR** [DorinR/KindleNoteViewer#17]
Main Areas:

- [x] Better home logo
- [x] Maybe move the navigation buttons somewhere so that its clear they are distinct from the home button
- [x] Fix that glitch where it doesn't update the UI when you logout #14
