### ISSUE TITLE
Clean up the single book view

### ISSUE THREAD

**Issue by DorinR** [DorinR/KindleNoteViewer#18]
Main tasks:

- [x] add global styles for certain components that is dark-mode compatible #27
- [x] sexier UI for each highlight #23 
- [x] sexier UI for each section #24 
- [x] sexier UI for the title and author card at the top #22 
- [ ] navigation button (like the back arrow on iOS) next to author card that can let user go back to "my books" page #26

Redesign:
- [x] Clicking on book should show a list of sections (should have some back button to go back to all books)
- [x] Clicking on a section should show highlights for given section (should have some back button to go back to all sections)
